# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20170212_2233'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reps', models.PositiveIntegerField(blank=True)),
                ('time', models.PositiveIntegerField(blank=True)),
                ('time_units', models.CharField(blank=True, choices=[('sec', 'Seconds'), ('min', 'Minutes'), ('hr', 'Hours'), ('d', 'days')], max_length=3)),
                ('weight', models.PositiveIntegerField(blank=True)),
                ('weight_units', models.CharField(blank=True, choices=[('lbs', 'Pounds'), ('kgs', 'Kilograms')], max_length=3)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sets', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='exercises.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_set_groups', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_groups', to='routines.Routine')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='routines.SetGroup'),
        ),
    ]
