# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_auto_20170304_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
